[DefaultOutputDestinationSettings = [DestinationDefinition = [Kind = "Reference", QueryName = "DefaultDestination", IsNewTarget = true], UpdateMethod = [Kind = "Replace"], DestinationTypeSettings = [Kind = "Table"]], StagingDefinition = [Kind = "FastCopy"]]
section Section1;
shared DefaultDestination = Lakehouse.Contents([EnableFolding = false]){[workspaceId = "cb65a0a4-f1b1-4adf-aaed-7cbff0148ef8"]}[Data]{[lakehouseId = "2dcbfe8e-d9e8-4137-95fe-44a4db0795aa"]}[Data];
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "invoice_header_DataDestination", IsNewTarget = true], Settings = [Kind = "Manual", AllowCreation = true, ColumnSettings = [Mappings = {[SourceColumnName = "Invoice ID", DestinationColumnName = "Invoice ID"], [SourceColumnName = "Invoice Number", DestinationColumnName = "Invoice Number"], [SourceColumnName = "Created Date", DestinationColumnName = "Created Date"], [SourceColumnName = "Updated Date", DestinationColumnName = "Updated Date"], [SourceColumnName = "Created By Login", DestinationColumnName = "Created By Login"], [SourceColumnName = "Created By Name", DestinationColumnName = "Created By Name"], [SourceColumnName = "Updated By Login", DestinationColumnName = "Updated By Login"], [SourceColumnName = "Updated By Name", DestinationColumnName = "Updated By Name"], [SourceColumnName = "Invoice Approval Date", DestinationColumnName = "Invoice Approval Date"], [SourceColumnName = "Invoice Date", DestinationColumnName = "Invoice Date"], [SourceColumnName = "Invoice Status", DestinationColumnName = "Invoice Status"], [SourceColumnName = "Supplier Name", DestinationColumnName = "Supplier Name"], [SourceColumnName = "Supplier Number", DestinationColumnName = "Supplier Number"], [SourceColumnName = "Date Received", DestinationColumnName = "Date Received"], [SourceColumnName = "Invoice Receipt Date_From Supplier", DestinationColumnName = "Invoice Receipt Date_From Supplier"], [SourceColumnName = "Net Due Date", DestinationColumnName = "Net Due Date"], [SourceColumnName = "GL Date", DestinationColumnName = "GL Date"], [SourceColumnName = "Payment Date", DestinationColumnName = "Payment Date"], [SourceColumnName = "Paid", DestinationColumnName = "Paid"], [SourceColumnName = "Inbox Entry Date", DestinationColumnName = "Inbox Entry Date"], [SourceColumnName = "COA", DestinationColumnName = "COA"], [SourceColumnName = "Hub Entity", DestinationColumnName = "Hub Entity"], [SourceColumnName = "Blanket PO", DestinationColumnName = "Blanket PO"], [SourceColumnName = "Currency", DestinationColumnName = "Currency"], [SourceColumnName = "Payment Term", DestinationColumnName = "Payment Term"], [SourceColumnName = "Shipping Term", DestinationColumnName = "Shipping Term"], [SourceColumnName = "GPO Processing Fee", DestinationColumnName = "GPO Processing Fee"], [SourceColumnName = "Printer Location", DestinationColumnName = "Printer Location"], [SourceColumnName = "National Office PO", DestinationColumnName = "National Office PO"], [SourceColumnName = "Invoice Description", DestinationColumnName = "Invoice Description"], [SourceColumnName = "LCO T3 Code", DestinationColumnName = "LCO T3 Code"], [SourceColumnName = "LCO T8 Code", DestinationColumnName = "LCO T8 Code"], [SourceColumnName = "LCO T9 Code", DestinationColumnName = "LCO T9 Code"], [SourceColumnName = "LCO Tax ID", DestinationColumnName = "LCO Tax ID"], [SourceColumnName = "Total", DestinationColumnName = "Total"], [SourceColumnName = "Delivery Method", DestinationColumnName = "Delivery Method"], [SourceColumnName = "On Time Payment", DestinationColumnName = "On Time Payment"], [SourceColumnName = "Scanning On Time", DestinationColumnName = "Scanning On Time"], [SourceColumnName = "Overdue From Supplier", DestinationColumnName = "Overdue From Supplier"], [SourceColumnName = "Registering On Time", DestinationColumnName = "Registering On Time"]}], DynamicSchema = true, UpdateMethod = [Kind = "Replace"], TypeSettings = [Kind = "Table"]]]}]
shared invoice_header = let
  Source = Sql.Database("10.202.8.50", "ProvisionAnalyticsv2"),
  #"Navigation 1" = Source{[Schema = "dbo", Item = "Invoice Header"]}[Data],
  #"Renamed columns" = Table.RenameColumns(#"Navigation 1", {{"Invoice Receipt Date (From Supplier)", "Invoice Receipt Date_From Supplier"}, {"National Office PO#", "National Office PO"}}),
  #"Removed columns" = Table.RemoveColumns(#"Renamed columns", {"InvoiceDaysToReceive"})
in
  #"Removed columns";
shared invoice_header_DataDestination = let
  Pattern = Lakehouse.Contents([CreateNavigationProperties = false, EnableFolding = false]),
  Navigation_1 = Pattern{[workspaceId = "cb65a0a4-f1b1-4adf-aaed-7cbff0148ef8"]}[Data],
  Navigation_2 = Navigation_1{[lakehouseId = "2dcbfe8e-d9e8-4137-95fe-44a4db0795aa"]}[Data],
  TableNavigation = Navigation_2{[Id = "invoice_header", ItemKind = "Table"]}?[Data]?
in
  TableNavigation;
